# Generated by Django 4.0.5 on 2022-08-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('correo', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=40)),
                ('cantidadIntegrantesFamilia', models.IntegerField()),
                ('tamañoAnimal', models.CharField(max_length=40)),
                ('animalInteresado', models.CharField(max_length=40)),
                ('localidad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('tamañoVivienda', models.CharField(max_length=40)),
                ('patioVivienda', models.CharField(max_length=40)),
            ],
        ),
    ]
