# Generated by Django 4.0.5 on 2022-08-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('correo', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=40)),
                ('perros', models.CharField(max_length=2)),
                ('gatos', models.CharField(max_length=2)),
                ('niños', models.CharField(max_length=2)),
                ('localidad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('hambientes', models.IntegerField()),
                ('patio', models.CharField(max_length=2)),
            ],
        ),
    ]
