# Generated by Django 4.0.5 on 2022-08-06 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_transito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adopcion',
            old_name='correo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='transito',
            old_name='correo',
            new_name='email',
        ),
    ]
