# Generated by Django 4.0.5 on 2022-08-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_rename_correo_adopcion_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('edad', models.IntegerField(max_length=2)),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.IntegerField(max_length=40)),
                ('tarjeta', models.IntegerField(max_length=16)),
                ('clave', models.IntegerField(max_length=3)),
                ('donacion', models.FloatField(max_length=10)),
            ],
        ),
    ]
