# Generated by Django 4.0.5 on 2022-08-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_donaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donaciones',
            name='clave',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donaciones',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donaciones',
            name='tarjeta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donaciones',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
