# Generated by Django 4.0.5 on 2022-08-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0007_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
