# Generated by Django 4.0.5 on 2022-08-09 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0008_delete_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
