# Generated by Django 4.0.5 on 2022-08-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0009_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=10)),
                ('contraseña', models.CharField(max_length=10)),
            ],
        ),
    ]
